name: test
on:
  push:
    branches:
    - "*"
  workflow_dispatch: 
    
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 


jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      TRIPLET: arm64-osx-ci
      vcpkgCommitId: '0f88ecb8528605f91980b90a2c5bad88e3cb565f'
      PresetName: ci

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - run: brew install nasm
    - name: Setup LibAtrac9
      run: |-
        pushd vendor
        if [ ! -d "LibAtrac9" ]; then
          git clone https://github.com/Thealexbarney/LibAtrac9.git --depth 1
        fi
        cd LibAtrac9/C
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          sed -i '' -e 's/,--version-script=libatrac9.version//g' Makefile
        fi
        if [ -z "${CC}" ]; then
          make
        else
          make CC="$CC"
        fi

        mkdir -p ../include/libatrac9
        mkdir -p ../libs
        cp bin/* ../libs/
        cp src/libatrac9.h ../include/libatrac9/
        popd
        echo "LIBATRAC9DIR=${{ github.workspace }}/vendor/LibAtrac9" >> $GITHUB_ENV
        find "${{ github.workspace }}/vendor/LibAtrac9"    
    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: ${{ env.PresetName }}
        buildPreset: build
    - name: "Print out cmake install script"
      if: always()
      run: cat ${{ github.workspace }}/ci-build/ci/cmake_install.cmake
    - run: 7z u test-file-${{ github.run_number }}-${{ github.sha }}.zip release/${{ env.PresetName }}/* 
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.1.0
      with:
        path: test-file-${{ github.run_number }}-${{ github.sha }}.zip
        name: release
